service: ${self:custom.global.product}-${self:custom.component}

plugins:
  - serverless-plugin-typescript

package:
  exclude:
    - '**/*.ts'

custom:
  component: pipelinets
  global: ${file(../serverless-global.yml)}

  specifiedStage: ${env:AWS_STAGE, opt:stage}
  stage: ${self:custom.specifiedStage, 'test'}

  timeout: 300

  bucket: ${self:service}-${self:custom.stage}

  steps:
    podcastCheckFeed:
      name: a-podcast-check-feed
      stageName: ${self:service}-${self:custom.stage}-${self:custom.steps.podcastCheckFeed.name}
      sqs:
        arn: arn:aws:sqs:${self:provider.region}:${self:custom.global.awsAccountId}:${self:custom.steps.podcastCheckFeed.stageName}
        url: https://sqs.${self:provider.region}.amazonaws.com/${self:custom.global.awsAccountId}/${self:custom.steps.podcastCheckFeed.stageName}
    episodeDownload:
      name: b-episode-download
      stageName: ${self:service}-${self:custom.stage}-${self:custom.steps.episodeDownload.name}
      sqs:
        arn: arn:aws:sqs:${self:provider.region}:${self:custom.global.awsAccountId}:${self:custom.steps.episodeDownload.stageName}
        url: https://sqs.${self:provider.region}.amazonaws.com/${self:custom.global.awsAccountId}/${self:custom.steps.episodeDownload.stageName}
    episodeSegmentStart:
      name: c-episode-segment-start
      stageName: ${self:service}-${self:custom.stage}-${self:custom.steps.episodeSegmentStart.name}
      sqs:
        arn: arn:aws:sqs:${self:provider.region}:${self:custom.global.awsAccountId}:${self:custom.steps.episodeSegmentStart.stageName}
        url: https://sqs.${self:provider.region}.amazonaws.com/${self:custom.global.awsAccountId}/${self:custom.steps.episodeSegmentStart.stageName}
    episodeSegmentComplete:
      name: d-episode-segment-complete
      stageName: ${self:service}-${self:custom.stage}-${self:custom.steps.episodeSegmentComplete.name}
      sqs:
        arn: arn:aws:sqs:${self:provider.region}:${self:custom.global.awsAccountId}:${self:custom.steps.episodeSegmentComplete.stageName}
        url: https://sqs.${self:provider.region}.amazonaws.com/${self:custom.global.awsAccountId}/${self:custom.steps.episodeSegmentComplete.stageName}
    episodeTranscribeStart:
      name: e-episode-transcribe-start
      stageName: ${self:service}-${self:custom.stage}-${self:custom.steps.episodeTranscribeStart.name}
      sqs:
        arn: arn:aws:sqs:${self:provider.region}:${self:custom.global.awsAccountId}:${self:custom.steps.episodeTranscribeStart.stageName}
        url: https://sqs.${self:provider.region}.amazonaws.com/${self:custom.global.awsAccountId}/${self:custom.steps.episodeTranscribeStart.stageName}
    episodeTranscribeComplete:
      name: f-episode-transcribe-complete
      stageName: ${self:service}-${self:custom.stage}-${self:custom.steps.episodeTranscribeComplete.name}
      sqs:
        arn: arn:aws:sqs:${self:provider.region}:${self:custom.global.awsAccountId}:${self:custom.steps.episodeTranscribeComplete.stageName}
        url: https://sqs.${self:provider.region}.amazonaws.com/${self:custom.global.awsAccountId}/${self:custom.steps.episodeTranscribeComplete.stageName}
    episodeInsert:
      name: g-episode-insert
      stageName: ${self:service}-${self:custom.stage}-${self:custom.steps.episodeInsert.name}
      sqs:
        arn: arn:aws:sqs:${self:provider.region}:${self:custom.global.awsAccountId}:${self:custom.steps.episodeInsert.stageName}
        url: https://sqs.${self:provider.region}.amazonaws.com/${self:custom.global.awsAccountId}/${self:custom.steps.episodeInsert.stageName}

  dynamodb:
    podcasts:
      name: ${self:custom.global.product}-${self:custom.stage}-${self:custom.global.dynamodb.podcasts.suffix}
      arn: arn:aws:dynamodb:${self:provider.region}:${self:custom.global.awsAccountId}:table/${self:custom.dynamodb.podcasts.name}
    episodes:
      name: ${self:custom.global.product}-${self:custom.stage}-${self:custom.global.dynamodb.episodes.suffix}
      arn: arn:aws:dynamodb:${self:provider.region}:${self:custom.global.awsAccountId}:table/${self:custom.dynamodb.episodes.name}
    statements:
      name: ${self:custom.global.product}-${self:custom.stage}-${self:custom.global.dynamodb.statements.suffix}
      arn: arn:aws:dynamodb:${self:provider.region}:${self:custom.global.awsAccountId}:table/${self:custom.dynamodb.statements.name}
    speakers:
      name: ${self:custom.global.product}-${self:custom.stage}-${self:custom.global.dynamodb.speakers.suffix}
      arn: arn:aws:dynamodb:${self:provider.region}:${self:custom.global.awsAccountId}:table/${self:custom.dynamodb.speakers.name}
    jobs:
      name: ${self:custom.global.product}-${self:custom.stage}-${self:custom.global.dynamodb.jobs.suffix}
      arn: arn:aws:dynamodb:${self:provider.region}:${self:custom.global.awsAccountId}:table/${self:custom.dynamodb.jobs.name}

  sns:
    topics:
      errors:
        name: ${self:service}-${self:custom.stage}-errors
        arn: arn:aws:sns:${self:provider.region}:${self:custom.global.awsAccountId}:${self:custom.sns.topics.errors.name}
      status:
        name: ${self:service}-${self:custom.stage}-status
        arn: arn:aws:sns:${self:provider.region}:${self:custom.global.awsAccountId}:${self:custom.sns.topics.status.name}

  transcoder:
    jobs:
      arn: arn:aws:elastictranscoder:${self:provider.region}:${self:custom.global.awsAccountId}:job/*
    presets:
      arn: arn:aws:elastictranscoder:${self:provider.region}:${self:custom.global.awsAccountId}:preset/*
    pipeline:
      ids:
        prod: 1535242598418-8hy4nc
        test: 1531803024408-reo2a2
        ian: 1534397495629-rlv3fd
        andrew: 1535242456767-0vcu3n
      id: ${self:custom.transcoder.pipeline.ids.${self:custom.stage}}
      arn: arn:aws:elastictranscoder:${self:provider.region}:${self:custom.global.awsAccountId}:pipeline/${self:custom.transcoder.pipeline.id}

  secrets:
    watson:
      transcribe:
        credentials:
          name: watson_transcribe_credentials
          arn: arn:aws:secretsmanager:${self:provider.region}:${self:custom.global.awsAccountId}:secret:watson_transcribe_credentials-rRBeuP

  logGroups:
    jobs:
      name: ${self:service}-${self:custom.stage}-job-logs
      arn: arn:aws:logs:${self:provider.region}:${self:custom.global.awsAccountId}:log-group:${self:custom.logGroups.jobs.name}

provider:
  name: aws
  runtime: nodejs8.10
  region: ${self:custom.global.region}
  stage: ${self:custom.stage}
  environment:
    PODCASTS_TABLE: ${self:custom.dynamodb.podcasts.name}
    EPISODES_TABLE: ${self:custom.dynamodb.episodes.name}
    STATEMENTS_TABLE: ${self:custom.dynamodb.statements.name}
    STATEMENTS_TABLE_WCU: ${self:custom.global.dynamodb.statements.wcu}
    SPEAKERS_TABLE: ${self:custom.dynamodb.speakers.name}
    JOBS_LOG_GROUP: ${self:custom.logGroups.jobs.name}
    JOBS_TABLE: ${self:custom.dynamodb.jobs.name}
    ERROR_TOPIC: ${self:custom.sns.topics.errors.arn}
    STATUS_TOPIC: ${self:custom.sns.topics.status.arn}
    BUCKET: ${self:custom.bucket}
    TRANSCODE_PIPELINE_ID: ${self:custom.transcoder.pipeline.id}
    WATSON_TRANSCRIBE_CREDENTIALS: ${self:custom.secrets.watson.transcribe.credentials.name}
    PODCAST_CHECK_FEED_QUEUE: ${self:custom.steps.podcastCheckFeed.sqs.url}
    EPISODE_DOWNLOAD_QUEUE: ${self:custom.steps.episodeDownload.sqs.url}
    EPISODE_SEGMENT_START_QUEUE: ${self:custom.steps.episodeSegmentStart.sqs.url}
    EPISODE_SEGMENT_COMPLETE_QUEUE: ${self:custom.steps.episodeSegmentComplete.sqs.url}
    EPISODE_TRANSCRIBE_START_QUEUE: ${self:custom.steps.episodeTranscribeStart.sqs.url}
    EPISODE_TRANSCRIBE_COMPLETE_QUEUE: ${self:custom.steps.episodeTranscribeComplete.sqs.url}
    EPISODE_INSERT_QUEUE: ${self:custom.steps.episodeInsert.sqs.url}
  iamRoleStatements:
    #
    # S3 Bucket Permissions
    #
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - arn:aws:s3:::${self:custom.bucket}/*

    #
    # DynamoDB Table Permissions
    #
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
        - dynamodb:DescribeTable
      Resource:
        - ${self:custom.dynamodb.podcasts.arn}
        - ${self:custom.dynamodb.episodes.arn}
        - ${self:custom.dynamodb.speakers.arn}
        - ${self:custom.dynamodb.statements.arn}
        - ${self:custom.dynamodb.jobs.arn}

    #
    # SNS Topic Publish Permissions
    #
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource:
        - ${self:custom.sns.topics.errors.arn}
        - ${self:custom.sns.topics.status.arn}

    #
    # SQS Send and Receive Permissions
    #
    - Effect: Allow
      Action:
        - SQS:ReceiveMessage
        - SQS:SendMessage
      Resource:
        - ${self:custom.steps.podcastCheckFeed.sqs.arn}
        - ${self:custom.steps.episodeDownload.sqs.arn}
        - ${self:custom.steps.episodeSegmentStart.sqs.arn}
        - ${self:custom.steps.episodeSegmentComplete.sqs.arn}
        - ${self:custom.steps.episodeTranscribeStart.sqs.arn}
        - ${self:custom.steps.episodeTranscribeComplete.sqs.arn}
        - ${self:custom.steps.episodeInsert.sqs.arn}

    #
    # Transcoder Permissions
    #
    - Effect: Allow
      Action:
        - elastictranscoder:Read*
        - elastictranscoder:List*
        - elastictranscoder:*Job
      Resource:
        - ${self:custom.transcoder.jobs.arn}
        - ${self:custom.transcoder.presets.arn}
        - ${self:custom.transcoder.pipeline.arn}

    #
    # AWS Transcription Service Permissions
    #
    - Effect: Allow
      Action:
        - transcribe:StartTranscriptionJob
      Resource: '*'

    #
    # AWS Transcription Service Permissions
    #
    - Effect: Allow
      Action:
        - transcribe:GetTranscriptionJob
        - transcribe:StartTranscriptionJob
      Resource: '*'

    #
    # AWS Secrets Manager Permissions
    #
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: ${self:custom.secrets.watson.transcribe.credentials.arn}

    #
    # AWS CloudWatch Logs Permissions
    #
    - Effect: Allow
      Action:
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: ${self:custom.logGroups.jobs.arn}:*

functions:
  #
  # Fetch, transcode and split the audio files
  #
  podcastCheckFeed:
    name: ${self:custom.steps.podcastCheckFeed.stageName}
    handler: src/functions/pipeline/${self:custom.steps.podcastCheckFeed.name}.handler
    timeout: ${self:custom.timeout}
    events:
      - sqs:
          arn: ${self:custom.steps.podcastCheckFeed.sqs.arn}
          batchSize: 1

  episodeDownload:
    name: ${self:custom.steps.episodeDownload.stageName}
    handler: src/functions/pipeline/${self:custom.steps.episodeDownload.name}.handler
    timeout: ${self:custom.timeout}
    events:
      - sqs:
          arn: ${self:custom.steps.episodeDownload.sqs.arn}
          batchSize: 1

  episodeSegmentStart:
    name: ${self:custom.steps.episodeSegmentStart.stageName}
    handler: src/functions/pipeline/${self:custom.steps.episodeSegmentStart.name}.handler
    timeout: ${self:custom.timeout}
    events:
      - sqs:
          arn: ${self:custom.steps.episodeSegmentStart.sqs.arn}
          batchSize: 1

  episodeSegmentComplete:
    name: ${self:custom.steps.episodeSegmentComplete.stageName}
    handler: src/functions/pipeline/${self:custom.steps.episodeSegmentComplete.name}.handler
    timeout: ${self:custom.timeout}
    events:
      - sqs:
          arn: ${self:custom.steps.episodeSegmentComplete.sqs.arn}
          batchSize: 1

  episodeTranscribeStart:
    name: ${self:custom.steps.episodeTranscribeStart.stageName}
    handler: src/functions/pipeline/${self:custom.steps.episodeTranscribeStart.name}.handler
    timeout: ${self:custom.timeout}
    events:
      - sqs:
          arn: ${self:custom.steps.episodeTranscribeStart.sqs.arn}
          batchSize: 1

  episodeTranscribeComplete:
    name: ${self:custom.steps.episodeTranscribeComplete.stageName}
    handler: src/functions/pipeline/${self:custom.steps.episodeTranscribeComplete.name}.handler
    timeout: ${self:custom.timeout}
    events:
      - sqs:
          arn: ${self:custom.steps.episodeTranscribeComplete.sqs.arn}
          batchSize: 1

  episodeInsert:
    name: ${self:custom.steps.episodeInsert.stageName}
    handler: src/functions/pipeline/${self:custom.steps.episodeInsert.name}.handler
    timeout: ${self:custom.timeout}
    events:
      - sqs:
          arn: ${self:custom.steps.episodeInsert.sqs.arn}
          batchSize: 1
    reservedConcurrency: 1

resources:
  Resources:
    #
    # S3 Bucket
    #
    bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}

    #
    # SNS for Errors
    #
    errorSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Boombox Pipeline Errors (${self:custom.stage})
        TopicName: ${self:custom.sns.topics.errors.name}

    errorSNSSubscription:
      Type: AWS::SNS::Subscription
      DependsOn:
        - errorSNSTopic
      Properties:
        Endpoint: boombox-pipeline-errors@googlegroups.com
        Protocol: 'email'
        TopicArn: ${self:custom.sns.topics.errors.arn}

    #
    # SNS for Status Updates
    #
    statusSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Boombox Pipeline Status (${self:custom.stage})
        TopicName: ${self:custom.sns.topics.status.name}

    statusSNSSubscription:
      Type: AWS::SNS::Subscription
      DependsOn:
        - statusSNSTopic
      Properties:
        Endpoint: boombox-pipeline-status@googlegroups.com
        Protocol: 'email'
        TopicArn: ${self:custom.sns.topics.status.arn}

    #
    # SQS Queues
    #
    podcastCheckFeedQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: ${self:custom.steps.podcastCheckFeed.stageName}
        VisibilityTimeout: ${self:custom.timeout}

    episodeDownloadQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: ${self:custom.steps.episodeDownload.stageName}
        VisibilityTimeout: ${self:custom.timeout}

    episodeSegmentStartQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: ${self:custom.steps.episodeSegmentStart.stageName}
        VisibilityTimeout: ${self:custom.timeout}

    episodeSegmentCompleteQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: ${self:custom.steps.episodeSegmentComplete.stageName}
        VisibilityTimeout: ${self:custom.timeout}

    episodeTranscribeStartQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: ${self:custom.steps.episodeTranscribeStart.stageName}
        VisibilityTimeout: ${self:custom.timeout}

    episodeTranscribeCompleteQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: ${self:custom.steps.episodeTranscribeComplete.stageName}
        VisibilityTimeout: ${self:custom.timeout}

    episodeInsertQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: ${self:custom.steps.episodeInsert.stageName}
        VisibilityTimeout: ${self:custom.timeout}

    jobLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: ${self:custom.logGroups.jobs.name}

    jobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamodb.jobs.name}
        AttributeDefinitions:
          - AttributeName: startTime
            AttributeType: S
        KeySchema:
          - AttributeName: startTime
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.global.dynamodb.jobs.rcu}
          WriteCapacityUnits: ${self:custom.global.dynamodb.jobs.wcu}
